message = {
    "birthday": 'With every year that passes, remember that you are becoming stronger, wiser and more compassionate! Happy birthday to someone who never stops dreaming and who never loses hope for the future. Remember that the best is yet to come!',
    "independence": ['Happy Independence day to your country, God bless'],
    "mothers_day": ['Happy Mothers day to the greatest mom, we love you'],
    "fathers_day": ['Happy Fathers day to you, you are the best!'],
    "international_women_day": 'Happy international womens day to all the beautiful and hardworking women around the world, you are a Queen  ',
    "international_men_day": 'Happy international mens day , thanks to the strength and support ',
    "global_family_day": ['Happy family day, wish your family a happy celebration'],
    "teachers_day": ['Happy teachers day, thanks for making impacts in our lives'],
    "engineering_day": ['Happy world tech day,keep engineering the world'],
    "computer_security_day": ['Its computer security day, never loose guard, be safe'],
    "world_friendship_day": ['You are a loving and caring friend, happy friendship day'],
    "world_african_child_day": ['Today is African childs day, you are great and  beautiful '],
    "world_human_right_day": ['dsdsdsdsds'],
    "world_mother_language_day": ['Be proud of the language, happy mother language day'],
    "world_violence_elimination_against_women_day": ['dsdsdsdsds'],
}
